import { defineStore } from 'pinia'

export const useServicesStore = defineStore('services', {
  state: () => ({
    services: [
      {
        id: 1,
        title: 'Mise à jour du profil professionnel',
        img: 'https://goog-maps.es/wp-content/uploads/2024/12/b75da78a12d390bfdf7fd23dd73a9eb2-300x158.jpg',
        price: '€220',
        period: 'unique',
        ref: 'GMB-PROFIL-220',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/9B6fZh60i5wMcdketebsc00',
        features: [
          'Mise à jour des informations',
          'Gestion des avis',
          'Optimisation du profil',
          'Gestion des notifications',
          'Suivi des performances',
          'Remise des accès propriétaire principale',
        ],
      },
      {
        id: 2,
        title: 'Liste des produits',
        img: 'https://goog-maps.es/wp-content/uploads/2025/01/OPTIMISATION-LISTES-DES-PRODUITS-min-300x209.png',
        price: '€290',
        period: 'unique',
        ref: 'GMB-PRODUITS-290',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/14keUY5Rk7UCb7ybJk',
        features: [
          'Création et optimisation',
          'Suivi des performances',
          'Mise à jour régulière',
          'Catégorisation stratégique',
          'Gestion des produits',
          'Remise des accès prioritaires',
        ],
      },
      {
        id: 3,
        title: 'GMB Référencement local',
        img: 'https://goog-maps.es/wp-content/uploads/2025/01/OPTIMISATION-ET-REFERENCEMENT-min-300x134.png',
        price: '€460',
        period: 'unique',
        ref: 'GMB-SEO-460',
        featured: true,
        stripeUrl: 'https://buy.stripe.com/fZe28c3Jc4IqdfGbJl',
        features: [
          'Optimisation du profil',
          "Accès fiche d'entreprise Google (Nv2)",
          'Activation des Mots-clés',
          'Création de QRcode pour encourager les avis',
          'Synchroniser les Réseaux Sociaux',
          "Intégration de l'IA pour la gestion du profil GMB",
          'Rapports personnalisés & Insights actionnables tous les 03 mois',
        ],
      },
      {
        id: 4,
        title: 'Service VIP',
        img: 'https://goog-maps.es/wp-content/uploads/2025/02/pexels-photo-3153204-3153204-200x300.jpg',
        price: '€500',
        period: 'único',
        ref: 'GMB-VIP-500',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/5kQbJ11cPfJm2g77l6dUY0P',
        features: [
          'Liste des produits',
          'Maintenance de profil',
          'Référencement local',
          'Sécurité & Assistance',
          'Suppression de profil',
        ],
      },
      {
        id: 5,
        title: 'Meta Optimisation',
        img: 'https://goog-maps.es/wp-content/uploads/2025/02/pexels-photo-3153204-3153204-200x300.jpg',
        price: '€297',
        period: 'unique',
        ref: 'META-OPT-297',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/8wM5kofrU1wefnO4gU',
        features: [
          'Sécurisation du profil',
          'Optimisation du profil',
          'Mise à jour professionnelle de la page',
          'Activation de la messagerie professionnelle',
          'Assistance IA',
          'Suppression des doublons',
        ],
      },
      {
        id: 6,
        title: 'Meta Ads Référencement',
        img: 'https://goog-maps.es/wp-content/uploads/2024/12/google_my_business_ofertas-802x480-removebg-preview-300x179.png',
        price: '€370',
        period: 'annuel',
        ref: 'META-ADS-370',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/7sI3cg3JccaS0sU8xb',
        features: [
          'Accès à double authentification',
          'Création de contenu engageant',
          'Mise à jour des informations',
          'Optimisation du profil',
          'Création de la campagne publicitaire',
          "Ciblage de l'audience",
          'Booster la page',
        ],
      },
      {
        id: 7,
        title: 'Site Web Pro',
        img: 'https://goog-maps.es/wp-content/uploads/2025/02/pexels-photo-4348404-4348404-300x204.jpg',
        price: '€1 500',
        period: 'Site web + Optimisation',
        ref: 'WEB-PRO-1500',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/bJefZh2gTap26wncFqdUY0Q',
        features: [
          'Création du site web',
          'Recevoir les réservations',
          'Adapté aux différents appareils',
          'Boîte e-mail professionnel',
          'Nom du domaine',
          'Hébergement',
          'Optimisation',
        ],
      },
      {
        id: 8,
        title: 'Créer un site Web – Réservation + Paiement',
        img: 'https://goog-maps.es/wp-content/uploads/2025/02/pexels-photo-4348404-4348404-300x204.jpg',
        price: '€2 500',
        period: 'Site web + Optimisation',
        ref: 'WEB-RESA-2500',
        featured: true,
        stripeUrl: 'https://buy.stripe.com/dRm4gz7BdgNq5sjbBmdUY0R',
        features: [
          'Création du site web',
          'Sécuriser le profil',
          'Sécuriser la galerie',
          'Synchroniser la galerie',
          "Catégoriser le nom d'établissement",
          'Corriger (adresse, horaires, nom)',
          'Activer la messagerie professionnelle',
          'Stabiliser le pointeur',
          'Total contrôle de la page',
          'Description & points forts activés',
        ],
      },
      {
        id: 9,
        title: 'PBX-Online',
        img: 'https://goog-maps.es/wp-content/uploads/2025/01/pexels-photo-19506332-19506332-scaled-1-300x200.jpg',
        price: '€25',
        period: '/ mois',
        ref: 'PBX-ONLINE-25',
        featured: false,
        stripeUrl: 'https://buy.stripe.com/bIYaEI7Zsfn46RidRx',
        features: [
          'PBX en nuage à partir de 25$/mois',
          'DID – La Costa Rica',
          'DID – USA',
          'DID – Canada',
          'DID – France',
          'DID – Espagne',
          'DID – La Chilie',
          'Administration & panneau de contrôle en ligne',
        ],
      },
    ],

    pbxFeatures: [
      'Application smartphone : une ou plusieurs extensions sur mobile',
      'Application PC, téléphone IP protocole SIP ou ligne fixe traditionnelle',
      'Messages WhatsApp Business depuis tous vos numéros locaux dans chaque pays',
      'Panneau de contrôle client en ligne 24h/24 et 7j/7',
      "Enregistrement des appels pour tous les utilisateurs ou certains d'entre eux",
      'De 1 à 1000 utilisateurs',
      'Vérification en ligne du solde et des tarifs d\'appel',
      'Numéro SDA local gratuit inclus',
      'Appels gratuits entre utilisateurs & succursales, quelle que soit la géographie',
      'Plate-forme multilingue',
      'Groupes d\'appels : ventes, gestion, support et autres départements',
      "Renvoi d'appel vers numéros nationaux et internationaux",
      'Réceptionniste virtuel IVR, message d\'accueil personnalisé',
      'VoiceMail – transfert des messages MP3 vers l\'e-mail de chaque utilisateur',
      'Attribution de préfixes pour les appels rapides',
      'Surveillance en direct et rapports d\'appels',
      'Gestion des utilisateurs depuis le panneau de contrôle',
      'Musique d\'attente personnalisable',
      'Option de téléchargement des rapports',
      'Différents niveaux de permissions pour utilisateurs multiples',
      'Statistiques des paiements effectués',
      'Numéros locaux disponibles dans plus de 70 pays',
    ],

    certifications: [
      { label: 'SEO for Growth',  img: 'https://goog-maps.es/wp-content/uploads/2024/12/seoforgrowthbadge_D-1-removebg-preview.png' },
      { label: 'Google SEO Cert', img: 'https://goog-maps.es/wp-content/uploads/2024/12/Google-Not-To-Provide-SEO-Certifications-To-SEO-Companies-removebg-preview.png' },
      { label: 'Certification 3', img: 'https://goog-maps.es/wp-content/uploads/2024/12/bea00486-f938-4966-8098-eee4733366c8-removebg-preview.png' },
      { label: 'Certification 4', img: 'https://goog-maps.es/wp-content/uploads/2024/12/b454fe89-c388-4997-aa54-b7c45b99a987-removebg-preview.png' },
      { label: 'Certification 5', img: 'https://goog-maps.es/wp-content/uploads/2024/12/1688557968911-removebg-preview.png' },
      { label: 'Certification 6', img: 'https://goog-maps.es/wp-content/uploads/2024/12/b914b1e1-a139-4110-b084-95e2a74a45f7-removebg-preview.png' },
      { label: 'GOOG-MAPS',       img: 'https://goog-maps.es/wp-content/uploads/2024/12/GOOG-removebg-preview-300x273.png' },
    ],
  }),
})
